### ISSUE TITLE
svg issues

### ISSUE THREAD

**Issue by JamesKyburz** [feross/hyperscript-attribute-to-property#1]
Great work! I love the idea of never writing className and htmlFor in hyperx / jsx again!

But our friend `svg` is not playing ball.
I noticed that this doesn't seem to work with svg elements :(

I'm not sure if it is limited to virtual-hyperscript's svg implementation, but [svg.js](https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/svg.js) uses setAttribute with the correct namespace of the property intead of  `svg.className=` which doesn't work with svg...

**Comment by feross** [comment]
I'm not sure how to fix this here. This module just lets you write `class` instead of `className`. If SVG worked fine before with `className`, then it ought to work with this too. Maybe you should open this as an issue on `hyperx` with a complete example?

**Comment by JamesKyburz** [comment]
SVG didn't work before with `className` it worked with `class` (due to `setProperty` usage) :( which is now is replaced with className.....

I can write a failing test for `hyperx`. I couldn't make up my mind if the issue should be here or there ;)

**Comment by feross** [comment]
@JamesKyburz Oh, I see. Yeah, I think the issue should be there, as this is functioning as intended. I think hyperx should probably not invoke this package when dealing with SVG tags. There's already a list of svg tags in the source code there, and I wouldn't want to duplicate that list here.

**Comment by JamesKyburz** [comment]
Added a note to https://github.com/Matt-Esch/virtual-dom/pull/271
It couldn't be fixed in `hyperx` because react uses className catch 22...
